#!/usr/bin/env bash
# This script install ngnix in the web-01 server
# shoul be listening on port 80

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw enable
sudo ufw allow 'Ngbix HTTP'
echo Holberton School > /var/www/html/index.html
sudo service ngnix restart
