#!/usr/bin/env bash
# This sccript redirection must be a “301 Moved Permanently”

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
