#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header (on web-01 and web-02)


sudo apt-get update
sudo apt-get install -y nginx
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
sudo service nginx start
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/xyz.html
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-available/default
sed -i "/server_name _/a add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
service nginx restart
