#!/usr/bin/env bash
#install load balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.5
apt-get -y update
apt-get -y install haproxy=1.5.\*
echo "frontend front
        bind *:80
        mode http
        default_backend back
backend back
        mode http
        balance roundrobin
        server 2008-web-01 35.185.94.34:80 check
        server 2008-web-02 3.91.70.36:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
