#!/usr/bin/env bash
# This bash script pings an IP address passed as an argument
# Ping the IP 5 times and if not argument passed print a msg
if [ "$1" ]
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
