#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
# only display username, user id and Home directory path for the user

FILE=/etc/passwd
while read line
do
	echo "$line" | cut -d ":" -f 1,3,6
done < $FILE
