#!/usr/bin/env bash
# Bash script configures an Ubuntu server with the below requirements
cp /etc/hosts new_hosts
sed -i 's/127.0.0.1/127.0.0.2/' new_hosts
sed -i '/localhost/ 8.8.8.8 facebook.com' new_hosts
cp -f new_hosts /etc/hosts
