#!/usr/bin/env bash
#  Run Nginx as Nginx
sudo pkill "apache2"
chmod 777 /etc/nginx/nginx.conf
chown -R nginx /etc/nginx
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
